Set-Content -Path "dbt_ecommerce\models\schema.yml" -Encoding utf8 -Value "version: 2

models:
  - name: stg_ecom
    columns:
      - name: invoice_no
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null
      - name: unit_price
        tests:
          - not_null

  - name: ecom_monthly_revenue
    columns:
      - name: invoice_month
        tests:
          - not_null
          - unique
      - name: revenue
        tests:
          - not_null

  - name: ecom_top_product
    columns:
      - name: stock_code
        tests:
          - not_null
          - unique

  - name: ecom_top_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: ecom_sales_by_country
    columns:
      - name: country
        tests:
          - not_null
          - unique"